### PR TITLE
Allow sending the password reset emails in cleartext rather than PGP

### PR DESCRIPTION
**Pull request by mig5**
@eloquence @ketudb as discussed

I have already deployed this branch and tested:

 * a password reset came through in 'clear text' (not GPG encrypted)
 * creating an issue still encrypts the notification (e.g other activity still uses encryption as desired)

### CODE REVIEW

**Comment by eloquence** [comment]
@mig5 It seems to work as expected! I'm wondering if, from a security perspective, it would make sense to make this logic conditional on whether a PGP key is configured. When it is, encrypting the password reset is arguably helpful defense in depth, it's just for the majority of users who don't have it set up that the plugin gets in the way, assuming folks are able to use PGP.

**Comment by echoesactiii** [comment]
> When it is, encrypting the password reset is arguably helpful defense in depth, it's just for the majority of users who don't have it set up that the plugin gets in the way, assuming folks are able to use PGP.

Yeah I'm inclined to agree. I don't love that redmine sends cleartext passwords at all, I'd rather it used a reset link or something, but that's beside the point -- if it _is_ going to be sending passwords out, I would prefer that at the very least it could take advantage of opportunistically encrypting the email?

**Comment by mig5** [comment]
@eloquence @ketudb please test again if possible. The change is actually a lot simpler when supporting that defense in depth method, I am simply setting the recipient to 'unchanged' (don't modify the email content) if they had no GPG key (and if the action was 'lost_password'). Everything else should work as it already was.

 * You have a GPG key, so password reset email is still sent encrypted to you
 * You have removed your GPG key (or are logged in as a user without one), and your password reset email is sent in clear text
 * You have removed your GPG key (or are logged in as a user without one), and *other* types of notifications by email (new issues, assigned to an issue etc) still have the message 'This mail was filtered for enhanced security. Follow this link and add your public PGP key to receive unfiltered encrypted mails' (they were correctly filtered due to no GPG key - *not* sent in clear text)

**Review by echoesactiii — APPROVED** [review]
This seems great to me. I'd love someone with more daily Redmine experience to double check that before merging, though!

**Comment by mig5** [comment]
(To be clear - this latest version of this PR has been in production in our Redmine for a week so hopefully any regressions would've been spotted by now :) )

**Pull request merged**
