### PR TITLE
Throw error message if the GPG key for a user has expired, when trying to send mail

### PR DESCRIPTION
**Pull request by mig5**
Works towards #1794

This checks for capability to encrypt using the GPG key. If it can't encrypt, an error message is logged, and the email is sent in 'filtered' form.

### CODE REVIEW

**Comment by mig5** [comment]
I think I can make this more broad than just expiry, and instead inspect the 'capability to encrypt'. Will follow up tomorrow.

**Comment by mig5** [comment]
Updated to check key for 'capability to encrypt', and it will now send the email in filtered form instead, rather than a near-silent discard.

**Review by echoesactiii — COMMENTED** [review]
Visual review looks fine to me!

**Review by echoesactiii — APPROVED** [review]

**Comment by mig5** [comment]
Thanks!

**Pull request merged**
